all:
	make -C ./Comission
	make -C ./Triangle
	make -C ./NextDate
test:
	make -C ./Comission test
	make -C ./Triangle test
	make -C ./NextDate test
clean:
	make -C ./Comission clean
	make -C ./Triangle clean
	make -C ./NextDate clean
