dist: trusty
language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
install:
        - sudo pip install codecov
script:
    - export CC=g++-6
    - export CCX=g++-6
    - make -C hw2 test
    - make -C hw2 show-gcov
branches:
    only:
        - master
after_success:
        - codecov -t "c2fa8c78-88d3-4ae5-b0ae-0085506a5355" -X gcov



