all:
	make -C ./Comission
	make -C ./Triangle
	make -C ./NextDate
test:
	make -C ./Comission test
	make -C ./Triangle test
	make -C ./NextDate test
gcov:
	make -C ./Comission show-gcov
	make -C ./Tirangle show-gcov
	make -C ./NextDate show-gcov
clean:
	make -C ./Comission clean
	make -C ./Triangle clean
	make -C ./NextDate clean
